### ISSUE TITLE
available from CRAN?

### ISSUE THREAD

**Issue by nick-youngblut** [guiblanchet/HMSC#16]
As far as I can tell, `HMSC` isn't available from CRAN. Package installation and management with packrat or conda would be facilitated by having `HMSC` available on CRAN. For instance, managing the dependency hierarchy of any packages that use `HMSC` as a dependency (at some possible point in the future) is going to be easier to deal with if your package is on CRAN. 

Are you planning (or currently working on) submitting `HMSC` to CRAN?

**Comment by nick-youngblut** [comment]
I just wanted to check whether there were any updates on this. Adding `HMSC` would really help with reproducing analysis environments (eg., with `packrat` or `conda`) that use the package. Otherwise, instructions for recreating the software environment would entail something like: "you can easily and rapidly recreate the environment, except for `HMSC`, which requires special installation instructions". The same goes for trying to install any R packages (or other software) that list `HMSC` as a dependency.

**Comment by guiblanchet** [comment]
This is a goal I have been having for a while and for which I am still working on. At the moment, there are still a few issues that I have been having with `HMSC` that have stopped me from adding it on the CRAN. I am currently working on these issues but I have been slowed down by a series of unexpected personal/professional events. 

With a bit of luck the whole thing should be on the CRAN sooner rather than later.
